title: "Alex's Dev Journey"
description: "Developer journey blog from Alex Peain â€“ backend, Django, APIs, DevOps, and learning notes."
author:
  name: "Alex Peain"
  email: "alexpeain@gmail.com"

url: "https://alexpeain.github.io"
baseurl: ""               # root site

# Make posts live under /blog/...
permalink: /blog/:year/:month/:day/:title.html


theme: minima


# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alexdocoding"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Alexpeain"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true
# This allows the excerpts to show on the homepage
show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

twitter_username: alexdocoding
github_username: Alexpeain

social:
  twitter: alexdocoding
  github: "https://github.com/Alexpeain"
