title: "Alex's Dev Journey"
description: "Developer journey blog from Alex Peain â€“ backend, Django, APIs, DevOps, and learning notes."
author:
  name: "Alex Peain"
  email: "alexpeain@gmail.com"

url: "https://alexpeain.github.io"
baseurl: ""               # root site

# Make posts live under /blog/...
permalink: /blog/:year/:month/:day/:title.html

theme: minima

# This allows the excerpts to show on the homepage
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

twitter_username: alexdocoding
github_username: Alexpeain

social:
  twitter: alexdocoding
  github: "https://github.com/Alexpeain"
