title: "Alex's Dev Journey"
description: "Developer journey blog from Alex Peain â€“ backend, Django, APIs, DevOps, and learning notes."
author:
  name: "Alex Peain"
  email: "alexpeain@gmail.com"

url: "https://alexpeain.github.io/blog"
baseurl: ""          # because this Jekyll site itself is served at /blog

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

twitter_username: alexdocoding
github_username: Alexpeain

social:
  twitter: alexdocoding
  github: "https://github.com/Alexpeain"
